services:
  - type: web
    name: vin-fastapi
    env: python
    plan: starter
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    pythonVersion: "3.12.13"
    envVars:
      - key: ENV
        value: production
