services:
  - type: web
    name: vin-fastapi
    env: python
    plan: starter
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    pythonVersion: "3.11.9"   # Must be properly indented under the service
    envVars:
      - key: ENV
        value: production
